### ISSUE TITLE
Hook "page:after" has been removed or is deprecated

### ISSUE THREAD

**Issue by BillClinton** [pm5/gitbook-plugin-json#5]
When I build I get the following warning:
`warn: Hook "page:after"" used by plugin "gitbook-plugin-json" has been removed or is deprecated`

My output.json contains an empty array
`[]`

According to this issue, Hook 'page:after'  has been removed in gitbook 2.01: https://github.com/GitbookIO/gitbook/issues/724

I believe this could be the reason I am getting no output in my output.json?

**Comment by pm5** [comment]
It could be.  Let me check about it.
